# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from joint.v1 import joint_pb2 as joint_dot_v1_dot_joint__pb2


class JointServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetJointEnableState = channel.unary_unary(
                '/joint.v1.JointService/SetJointEnableState',
                request_serializer=joint_dot_v1_dot_joint__pb2.SetJointEnableStateRequest.SerializeToString,
                response_deserializer=joint_dot_v1_dot_joint__pb2.SetJointEnableStateResponse.FromString,
                _registered_method=True)
        self.SetJointZeroPosition = channel.unary_unary(
                '/joint.v1.JointService/SetJointZeroPosition',
                request_serializer=joint_dot_v1_dot_joint__pb2.SetJointZeroPositionRequest.SerializeToString,
                response_deserializer=joint_dot_v1_dot_joint__pb2.SetJointZeroPositionResponse.FromString,
                _registered_method=True)
        self.SetJointMinPosition = channel.unary_unary(
                '/joint.v1.JointService/SetJointMinPosition',
                request_serializer=joint_dot_v1_dot_joint__pb2.SetJointMinPositionRequest.SerializeToString,
                response_deserializer=joint_dot_v1_dot_joint__pb2.SetJointMinPositionResponse.FromString,
                _registered_method=True)
        self.SetJointMaxPosition = channel.unary_unary(
                '/joint.v1.JointService/SetJointMaxPosition',
                request_serializer=joint_dot_v1_dot_joint__pb2.SetJointMaxPositionRequest.SerializeToString,
                response_deserializer=joint_dot_v1_dot_joint__pb2.SetJointMaxPositionResponse.FromString,
                _registered_method=True)
        self.SetJointMaxSpeed = channel.unary_unary(
                '/joint.v1.JointService/SetJointMaxSpeed',
                request_serializer=joint_dot_v1_dot_joint__pb2.SetJointMaxSpeedRequest.SerializeToString,
                response_deserializer=joint_dot_v1_dot_joint__pb2.SetJointMaxSpeedResponse.FromString,
                _registered_method=True)
        self.SetJointMaxAcceleration = channel.unary_unary(
                '/joint.v1.JointService/SetJointMaxAcceleration',
                request_serializer=joint_dot_v1_dot_joint__pb2.SetJointMaxAccelerationRequest.SerializeToString,
                response_deserializer=joint_dot_v1_dot_joint__pb2.SetJointMaxAccelerationResponse.FromString,
                _registered_method=True)


class JointServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetJointEnableState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointZeroPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointMinPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointMaxPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointMaxSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointMaxAcceleration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JointServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetJointEnableState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointEnableState,
                    request_deserializer=joint_dot_v1_dot_joint__pb2.SetJointEnableStateRequest.FromString,
                    response_serializer=joint_dot_v1_dot_joint__pb2.SetJointEnableStateResponse.SerializeToString,
            ),
            'SetJointZeroPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointZeroPosition,
                    request_deserializer=joint_dot_v1_dot_joint__pb2.SetJointZeroPositionRequest.FromString,
                    response_serializer=joint_dot_v1_dot_joint__pb2.SetJointZeroPositionResponse.SerializeToString,
            ),
            'SetJointMinPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointMinPosition,
                    request_deserializer=joint_dot_v1_dot_joint__pb2.SetJointMinPositionRequest.FromString,
                    response_serializer=joint_dot_v1_dot_joint__pb2.SetJointMinPositionResponse.SerializeToString,
            ),
            'SetJointMaxPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointMaxPosition,
                    request_deserializer=joint_dot_v1_dot_joint__pb2.SetJointMaxPositionRequest.FromString,
                    response_serializer=joint_dot_v1_dot_joint__pb2.SetJointMaxPositionResponse.SerializeToString,
            ),
            'SetJointMaxSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointMaxSpeed,
                    request_deserializer=joint_dot_v1_dot_joint__pb2.SetJointMaxSpeedRequest.FromString,
                    response_serializer=joint_dot_v1_dot_joint__pb2.SetJointMaxSpeedResponse.SerializeToString,
            ),
            'SetJointMaxAcceleration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointMaxAcceleration,
                    request_deserializer=joint_dot_v1_dot_joint__pb2.SetJointMaxAccelerationRequest.FromString,
                    response_serializer=joint_dot_v1_dot_joint__pb2.SetJointMaxAccelerationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joint.v1.JointService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joint.v1.JointService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JointService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetJointEnableState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joint.v1.JointService/SetJointEnableState',
            joint_dot_v1_dot_joint__pb2.SetJointEnableStateRequest.SerializeToString,
            joint_dot_v1_dot_joint__pb2.SetJointEnableStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointZeroPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joint.v1.JointService/SetJointZeroPosition',
            joint_dot_v1_dot_joint__pb2.SetJointZeroPositionRequest.SerializeToString,
            joint_dot_v1_dot_joint__pb2.SetJointZeroPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointMinPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joint.v1.JointService/SetJointMinPosition',
            joint_dot_v1_dot_joint__pb2.SetJointMinPositionRequest.SerializeToString,
            joint_dot_v1_dot_joint__pb2.SetJointMinPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointMaxPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joint.v1.JointService/SetJointMaxPosition',
            joint_dot_v1_dot_joint__pb2.SetJointMaxPositionRequest.SerializeToString,
            joint_dot_v1_dot_joint__pb2.SetJointMaxPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointMaxSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joint.v1.JointService/SetJointMaxSpeed',
            joint_dot_v1_dot_joint__pb2.SetJointMaxSpeedRequest.SerializeToString,
            joint_dot_v1_dot_joint__pb2.SetJointMaxSpeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointMaxAcceleration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joint.v1.JointService/SetJointMaxAcceleration',
            joint_dot_v1_dot_joint__pb2.SetJointMaxAccelerationRequest.SerializeToString,
            joint_dot_v1_dot_joint__pb2.SetJointMaxAccelerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
