# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from motion.v1 import motion_pb2 as motion_dot_v1_dot_motion__pb2


class MotionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MoveJ = channel.unary_unary(
                '/motion.v1.MotionService/MoveJ',
                request_serializer=motion_dot_v1_dot_motion__pb2.MoveJRequest.SerializeToString,
                response_deserializer=motion_dot_v1_dot_motion__pb2.MoveJResponse.FromString,
                _registered_method=True)
        self.JogJoint = channel.unary_unary(
                '/motion.v1.MotionService/JogJoint',
                request_serializer=motion_dot_v1_dot_motion__pb2.JogJointRequest.SerializeToString,
                response_deserializer=motion_dot_v1_dot_motion__pb2.JogJointResponse.FromString,
                _registered_method=True)


class MotionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MoveJ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JogJoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MoveJ': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveJ,
                    request_deserializer=motion_dot_v1_dot_motion__pb2.MoveJRequest.FromString,
                    response_serializer=motion_dot_v1_dot_motion__pb2.MoveJResponse.SerializeToString,
            ),
            'JogJoint': grpc.unary_unary_rpc_method_handler(
                    servicer.JogJoint,
                    request_deserializer=motion_dot_v1_dot_motion__pb2.JogJointRequest.FromString,
                    response_serializer=motion_dot_v1_dot_motion__pb2.JogJointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'motion.v1.MotionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('motion.v1.MotionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MoveJ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.v1.MotionService/MoveJ',
            motion_dot_v1_dot_motion__pb2.MoveJRequest.SerializeToString,
            motion_dot_v1_dot_motion__pb2.MoveJResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JogJoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.v1.MotionService/JogJoint',
            motion_dot_v1_dot_motion__pb2.JogJointRequest.SerializeToString,
            motion_dot_v1_dot_motion__pb2.JogJointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
